#!/usr/bin/env sh

# global settings
yabai -m config                                 \
    mouse_follows_focus         off            \
    focus_follows_mouse         off            \
    window_origin_display      default         \
    window_placement           second_child    \
    window_zoom_persist        on              \
    window_shadow              off             \
    window_animation_duration  0.0             \
    window_animation_frame_rate 120            \
    window_opacity_duration    0.0             \
    active_window_opacity      1.0             \
    normal_window_opacity      0.90            \
    window_opacity             on              \
    insert_feedback_color      0xffd75f5f      \
    split_ratio               0.50             \
    split_type               auto              \
    auto_balance             off              \
    layout                   bsp               \
    top_padding             0                 \
    bottom_padding          0                 \
    left_padding            0                 \
    right_padding           0                 \
    window_gap              0

# mouse support
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap

# Specific app rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off sticky=on
yabai -m rule --add app="^System Information$" manage=off sticky=on
yabai -m rule --add app="^Activity Monitor$" manage=off sticky=on
yabai -m rule --add app="^Preview$" manage=off sticky=on
yabai -m rule --add app="^Messages$" manage=off sticky=on
yabai -m rule --add app="^Digital Color Meter$" manage=off sticky=on
yabai -m rule --add app="^main" manage=off sticky=on
yabai -m rule --add app="^Wootility" manage=off sticky=on
